### ISSUE TITLE
Have inputs to Placzek be calculated from ParentWorkspace if not provided

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/mantid_total_scattering#15]
After removing the need for the characterization file, the input for L2 and Polar need to be calculated. 

These should be calculated at the "Initial Grouping" level at this point in the main script: https://github.com/marshallmcdonnell/mantid_total_scattering/blob/f3a1a6ff9f96900b385f912e9a72138ca20d5dea/mantid_total_scattering.py#L522

Fix is necessary for PR #14

**Comment by marshallmcdonnell** [comment]
Trying to use this to finally get Placzek stuff into Mantid. Will require 3 new algorithms for the workflow:
1) Efficiency calculator 
    Issue: https://github.com/mantidproject/mantid/issues/24432
    PR: https://github.com/mantidproject/mantid/pull/24451

2) Fit and functionalize incident spectrum
    Issue: N/A
    PR: N/A

3) Placzek algorithm
    Issue: N/A
    PR: N/A

**Comment by ElliotAOram** [comment]
I believe once this is fixed, the POLARIS system test should run again

**Comment by marshallmcdonnell** [comment]
This should be ready now with a refactor to add the following Mantid algorithms:
 - [CalculateEfficiencyCorrection](https://docs.mantidproject.org/nightly/algorithms/CalculateEfficiencyCorrection-v1.html)
 - [FitIncidentSpectrum](https://docs.mantidproject.org/nightly/algorithms/FitIncidentSpectrum-v1.html)
 - [CalculatePlaczekSelfScattering](https://docs.mantidproject.org/nightly/algorithms/CalculatePlaczekSelfScattering-v1.html)

The file below was used in the PR for `CalculatePlaczekSelfScattering` which shows the workflow for all three of these algorithms being used together:

[placzek_correction_test_instrument_data.py.txt](https://github.com/marshallmcdonnell/mantid_total_scattering/files/3686304/placzek_correction_test_instrument_data.py.txt)

**Comment by Kvieta1990** [comment]
Routine redesigned concerning Placzek implementation.
