### ISSUE TITLE
Absorption correction refactor for Paalman-Pings type 

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/mantid_total_scattering#18]
**This mainly involves work in Mantid**

- [ ] Need to analyze Martyn Gigg's absorption correction base class [`AbsorptionCorrection`](https://github.com/mantidproject/mantid/blob/f6507f371f080d92bcec080fb3a223c8c85077ea/Framework/Algorithms/src/AbsorptionCorrection.cpp) to determine what is needed to add in the capability to do Paalman-Pings style correction (sample, sample + can, sample + can + apparatus, etc.).

- [ ] Example for a cylinder that uses this base class is [`CylinderAbsorption`](http://docs.mantidproject.org/nightly/algorithms/CylinderAbsorption-v1.html)

**Comment by Kvieta1990** [comment]
Implementation done through user story system.
