### ISSUE TITLE
Add high Q self scattering level  and the slope by fitting a line

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/mantid_total_scattering#51]
Reported by: Matt Tucker

Issue: We need to get `mantidtotalscattering` to write out the high Q self scattering level of each of the banks( and the merged set) and the slope by fitting a line to a set range. This would be very useful and help when tweaking the powder density to get the scale correct.

Relevant "dead" code exists at the following locations, needs refactoring with current reduction:
 - Self-scattering stuff and fit setup: https://github.com/marshallmcdonnell/mantid_total_scattering/blob/64c112a9a8d5a9fa013378a32331ebfd84ca6b53/total_scattering/reduction/total_scattering_reduction.py#L1227-L1242
 - Actual fitting and output: https://github.com/marshallmcdonnell/mantid_total_scattering/blob/64c112a9a8d5a9fa013378a32331ebfd84ca6b53/total_scattering/reduction/total_scattering_reduction.py#L1322-L1347

**Comment by Kvieta1990** [comment]
Implementation done through user story system.
