### ISSUE TITLE
Refactor input JSON structure for Output section

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/mantid_total_scattering#64]
Want to create this as the new JSON structure:
```
{  "Title": "title",
   "Facility": "SNS",
   "Instrument": "NOM",
   "CacheDir": "./tmp",
   "Merging": {...}
   "Sample": {...},
   "Normalization": {...},
   "Calibration": {...},
   "AlignAndFocusArgs": {...},
   "Output": {
        "Directory": "./",
        "PDF": {...},
        "Rietveld": {...}
    }
}
```

Notable Changes:
 - `OutputDir` changes to `Output: {`Directory`: ""}`
 - `The plan for the `Rietveld` section will be (with similar for PDF):
	```
	{ ...,
		"Rietveld": {
			"GSAS": "output.gss",
			"FullProf": "output.txt",
			"DMin": [0.52, 0.31, 0.18, 0.13, 0.13, 1.05],
			"DMax": [6.28, 6.28, 3.4, 1.9, 1.54, 12.57]
		}
	}
	```

This is Re #48

**Comment by marshallmcdonnell** [comment]
Probably should add a "main" key word `"Version"` to handle new JSON structures.
If so, then current version will be:
`"Version": 0.2`

and fixing this issue should probably be:
`"Version": 0.3`
since a pretty large change.

Also, can we support yaml as well?

**Comment by Kvieta1990** [comment]
This issue has been covered by PR [![GitHub issue/pull request detail](https://img.shields.io/github/issues/detail/state/neutrons/mantid_total_scattering/124)](https://github.com/neutrons/mantid_total_scattering/issues/124)

Now the min and max for each bank is determined in a robust manner.
