### ISSUE TITLE
Refactor Multiple Scattering

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/mantid_total_scattering#67]
Need to get just the multiple scattering corrections from Mantid algorithms and use: https://docs.mantidproject.org/nightly/algorithms/MayersSampleCorrection-v1.html

Want to use the multiple scattering correction (ie `M_x` with `x` = `sca`, `ca, or `a) in the same way as the following reduction equation:
![image](https://user-images.githubusercontent.com/17032543/66137359-f64e6c80-e5ca-11e9-934b-6f98f5c50982.png)

**Comment by Kvieta1990** [comment]
Generic routine for doing multiple scattering has already been implemented.
